//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinchukov.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int IdRegistration { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IdEmployee { get; set; }
        public int IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
